### ISSUE TITLE
onions_version does not allow explicit version 2

### ISSUE THREAD

**Issue by trobotham** [systemli/ansible-role-onion#2]
It appears that you cannot force onions_version to "2", it simply ignores the "onion_version: 2" param.

**Comment by xshadow** [comment]
Could you explain what you mean? 

The default is v2. So it's forced to v2 services, if you don't set anything or set `onion_version: 2` 

Only if you set `onion_version: 3`, HiddenServices in Version 3 are created. .

**Comment by xshadow** [comment]
It seems that v3 is the default by now: 

" v3 onion client support exists in all TBBs. As of tor-0.3.5, v3 onions are the default onion service version on the service-side. v2 onions still supported on client and service-side. Users are encouraged to use v3 onions and help us find/fix out any bugs. "

https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions#Howtoconnecttothetesthubfornextgenonionservices

**Comment by trobotham** [comment]
This is no longer true as of 0.3.5, v3 is absolutely default:

"v3 onion client support exists in all TBBs. As of tor-0.3.5, v3 onions are the default onion service version on the service-side. v2 onions still supported on client and service-side. Users are encouraged to use v3 onions and help us find/fix out any bugs. "

**Comment by trobotham** [comment]
Yeah, v3 is default so if I wanted to use v2 that means I would have to explicitly set it which ansible will not let me know with the current templating.

**Comment by xshadow** [comment]
Correct. But that's is at the moment a intended behavior of Tor internals. With versions below < 0.3.5. it would work as expected. 

I will have a look into it, if there is an option to change Tor's behavior, when using >= 0.3.5

**Comment by xshadow** [comment]
Should be possible.
