### ISSUE TITLE
TOR reload

### ISSUE THREAD

**Issue by trobotham** [systemli/ansible-role-onion#3]
https://github.com/systemli/ansible-role-onion/blob/master/tasks/main.yml#L114
rather then restarting tor, should likely consider gracefully reloading

See: https://stem.torproject.org/faq.html#how-do-i-reload-my-torrc

**Comment by xshadow** [comment]
Hello @trobotham, the reload does not seem to work for v3 onion services. That's why we had to change it to restart: https://github.com/systemli/ansible-role-onion/commit/047a6041b42348d134118fd6497c67d21b77c1dc

**Comment by trobotham** [comment]
is there a way that I can get this set to a variable? I am not so sure that a full restart is still required with the latest version of Tor but even if it is, the ability to set this via variable with a default of restarted would be great. The need for this is if you use the Tor HS for something that needs persistent connections, restarting breaks said connection.

It seems that you fixed this in 530d54c however, you still restart it via handlers at:

https://github.com/systemli/ansible-role-onion/blob/master/tasks/main.yml#L71
https://github.com/systemli/ansible-role-onion/blob/master/tasks/main.yml#L85
https://github.com/systemli/ansible-role-onion/blob/master/tasks/main.yml#L99

**Comment by xshadow** [comment]
This seems not to be sufficient anymore. I had to change the method back to restart.
